// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	MtcUser
	ExternalId
	Imsi
	CreateExternalId
	GetImsiFromExtId
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MtcUser struct {
	Imsi        string        `protobuf:"bytes,1,opt,name=imsi" json:"imsi,omitempty"`
	ExternalIds []*ExternalId `protobuf:"bytes,2,rep,name=externalIds" json:"externalIds,omitempty"`
}

func (m *MtcUser) Reset()                    { *m = MtcUser{} }
func (m *MtcUser) String() string            { return proto.CompactTextString(m) }
func (*MtcUser) ProtoMessage()               {}
func (*MtcUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MtcUser) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

func (m *MtcUser) GetExternalIds() []*ExternalId {
	if m != nil {
		return m.ExternalIds
	}
	return nil
}

type ExternalId struct {
	LocalIdentifier string `protobuf:"bytes,1,opt,name=localIdentifier" json:"localIdentifier,omitempty"`
	Domain          string `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
}

func (m *ExternalId) Reset()                    { *m = ExternalId{} }
func (m *ExternalId) String() string            { return proto.CompactTextString(m) }
func (*ExternalId) ProtoMessage()               {}
func (*ExternalId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExternalId) GetLocalIdentifier() string {
	if m != nil {
		return m.LocalIdentifier
	}
	return ""
}

func (m *ExternalId) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type Imsi struct {
	Imsi string `protobuf:"bytes,1,opt,name=imsi" json:"imsi,omitempty"`
}

func (m *Imsi) Reset()                    { *m = Imsi{} }
func (m *Imsi) String() string            { return proto.CompactTextString(m) }
func (*Imsi) ProtoMessage()               {}
func (*Imsi) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Imsi) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type CreateExternalId struct {
	Imsi string `protobuf:"bytes,1,opt,name=imsi" json:"imsi,omitempty"`
}

func (m *CreateExternalId) Reset()                    { *m = CreateExternalId{} }
func (m *CreateExternalId) String() string            { return proto.CompactTextString(m) }
func (*CreateExternalId) ProtoMessage()               {}
func (*CreateExternalId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateExternalId) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type GetImsiFromExtId struct {
	ExtId string `protobuf:"bytes,1,opt,name=extId" json:"extId,omitempty"`
}

func (m *GetImsiFromExtId) Reset()                    { *m = GetImsiFromExtId{} }
func (m *GetImsiFromExtId) String() string            { return proto.CompactTextString(m) }
func (*GetImsiFromExtId) ProtoMessage()               {}
func (*GetImsiFromExtId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetImsiFromExtId) GetExtId() string {
	if m != nil {
		return m.ExtId
	}
	return ""
}

func init() {
	proto.RegisterType((*MtcUser)(nil), "MtcUser")
	proto.RegisterType((*ExternalId)(nil), "ExternalId")
	proto.RegisterType((*Imsi)(nil), "Imsi")
	proto.RegisterType((*CreateExternalId)(nil), "CreateExternalId")
	proto.RegisterType((*GetImsiFromExtId)(nil), "GetImsiFromExtId")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Einf_Service service

type Einf_ServiceClient interface {
	CreateExternalIdentity(ctx context.Context, in *CreateExternalId, opts ...grpc.CallOption) (*ExternalId, error)
	GetImsiFromExternalId(ctx context.Context, in *GetImsiFromExtId, opts ...grpc.CallOption) (*Imsi, error)
}

type einf_ServiceClient struct {
	cc *grpc.ClientConn
}

func NewEinf_ServiceClient(cc *grpc.ClientConn) Einf_ServiceClient {
	return &einf_ServiceClient{cc}
}

func (c *einf_ServiceClient) CreateExternalIdentity(ctx context.Context, in *CreateExternalId, opts ...grpc.CallOption) (*ExternalId, error) {
	out := new(ExternalId)
	err := grpc.Invoke(ctx, "/Einf_Service/CreateExternalIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *einf_ServiceClient) GetImsiFromExternalId(ctx context.Context, in *GetImsiFromExtId, opts ...grpc.CallOption) (*Imsi, error) {
	out := new(Imsi)
	err := grpc.Invoke(ctx, "/Einf_Service/GetImsiFromExternalId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Einf_Service service

type Einf_ServiceServer interface {
	CreateExternalIdentity(context.Context, *CreateExternalId) (*ExternalId, error)
	GetImsiFromExternalId(context.Context, *GetImsiFromExtId) (*Imsi, error)
}

func RegisterEinf_ServiceServer(s *grpc.Server, srv Einf_ServiceServer) {
	s.RegisterService(&_Einf_Service_serviceDesc, srv)
}

func _Einf_Service_CreateExternalIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExternalId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Einf_ServiceServer).CreateExternalIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Einf_Service/CreateExternalIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Einf_ServiceServer).CreateExternalIdentity(ctx, req.(*CreateExternalId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Einf_Service_GetImsiFromExternalId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImsiFromExtId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Einf_ServiceServer).GetImsiFromExternalId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Einf_Service/GetImsiFromExternalId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Einf_ServiceServer).GetImsiFromExternalId(ctx, req.(*GetImsiFromExtId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Einf_Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Einf_Service",
	HandlerType: (*Einf_ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExternalIdentity",
			Handler:    _Einf_Service_CreateExternalIdentity_Handler,
		},
		{
			MethodName: "GetImsiFromExternalId",
			Handler:    _Einf_Service_GetImsiFromExternalId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0xa4, 0xb5, 0xad, 0xf8, 0x22, 0xda, 0x3e, 0xb4, 0x84, 0x9c, 0x4a, 0x0e, 0x92, 0x8b, 0x0b,
	0xd6, 0x8b, 0x77, 0x89, 0x12, 0x50, 0x0f, 0x15, 0xcf, 0xb2, 0x26, 0xaf, 0xb2, 0xd0, 0xdd, 0x95,
	0xdd, 0x87, 0x54, 0xfc, 0x79, 0xd9, 0x18, 0x35, 0x2e, 0xbd, 0xcd, 0xbc, 0x19, 0x66, 0x86, 0x5d,
	0x38, 0xd2, 0xe4, 0xbd, 0x7c, 0x25, 0x2f, 0xde, 0x9c, 0x65, 0x9b, 0xdf, 0xc1, 0xfe, 0x3d, 0xd7,
	0x4f, 0x9e, 0x1c, 0x22, 0x8c, 0x94, 0xf6, 0x2a, 0x1d, 0x2c, 0x06, 0xc5, 0xc1, 0xaa, 0xc5, 0x78,
	0x0e, 0x09, 0x6d, 0x99, 0x9c, 0x91, 0x9b, 0xaa, 0xf1, 0xe9, 0x70, 0xb1, 0x57, 0x24, 0xcb, 0x44,
	0x94, 0xbf, 0xb7, 0x55, 0x5f, 0xcf, 0x1f, 0x00, 0xfe, 0x24, 0x2c, 0xe0, 0x78, 0x63, 0xeb, 0x00,
	0xc9, 0xb0, 0x5a, 0x2b, 0x72, 0x5d, 0x76, 0x7c, 0xc6, 0x39, 0x4c, 0x1a, 0xab, 0xa5, 0x32, 0xe9,
	0xb0, 0x35, 0x74, 0x2c, 0xcf, 0x60, 0x54, 0x85, 0x19, 0x3b, 0xa6, 0xe5, 0x67, 0x30, 0xbd, 0x76,
	0x24, 0x99, 0x7a, 0x8d, 0xbb, 0x7c, 0x05, 0x4c, 0x6f, 0x89, 0x43, 0xcc, 0x8d, 0xb3, 0xba, 0xdc,
	0x72, 0xd5, 0xe0, 0x09, 0x8c, 0x29, 0x80, 0xce, 0xf8, 0x4d, 0x96, 0x9f, 0x70, 0x58, 0x2a, 0xb3,
	0x7e, 0x7e, 0x24, 0xf7, 0xae, 0x6a, 0xc2, 0x2b, 0x98, 0xc7, 0x0d, 0x61, 0x31, 0x7f, 0xe0, 0x4c,
	0xc4, 0x42, 0xd6, 0x7f, 0x14, 0xbc, 0x80, 0xd3, 0xff, 0x9d, 0x3f, 0xc2, 0x4c, 0xc4, 0x5b, 0xb2,
	0xb1, 0x08, 0xfc, 0x65, 0xd2, 0xfe, 0xc7, 0xe5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x7f,
	0x39, 0xc7, 0xa1, 0x01, 0x00, 0x00,
}
